version: "2"
services:
  ngix:
    image: "nginx"
    volumes:
      - ./HTML:/usr/share/nginx/html
      - ./nginx_configs/conf.d:/etc/nginx/conf.d
      - ./nginx_configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "4443:443"
    expose:
      - 80
      - 443
  node1:
    image: "node:8"
    user: node
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./node1c:/home/node
    ports:
      - "8081:8081"
    expose:
      - 8081
    command: "npm start"
  node2:
    image: "node:8"
    user: node
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./node1c:/home/node
    ports:
      - "8082:8081"
    expose:
      - 8081
    command: "npm start"
#  couch:
#    image: "couchdb"
#    environment:
#      - COUCHDB_USER=admin
#      - COUCHDB_PASSWORD=password
#    ports: 
#      - "5984:5984"
#    expose: 
#      - 5984
