version: "2"
services:
  ngix:
    image: "nginx"
    volumes:
      - /home/eurus/uni/LTW-PROJ/LTW_PRJ/HTML:/usr/share/nginx/html
    ports:
      - "8080:80"
      - "4443:443"
    expose:
      - 80
      - 443
